name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dowload Repository
        uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build proyect
        run: ./gradlew build
